Logowanie rejestracja
VenetianDevil/UJ_PAI_grupowy pull request #1
Opened 2022-06-28 12:03 UTC by Dcisowski

Please Review

2022-07-01 22:43 UTC, Dcisowski commented
Please Review

2022-07-03 21:20 UTC, VenetianDevil commented
Logowanie chyba działa OK.
Z rejestracją są problemy;
Raz mi sie zarejestrowało i zwróciło token, ale pusty obiekt user_data
Za drugim razem też zarejestrował, ale wywaliło na backendzie błąd 
`{ login: 'test1', password: 'test', type: 2 }
Error: WHERE parameter "email" has invalid "undefined" value`
i zwróciło mi na front "stack": 
![image](https://user-images.githubusercontent.com/33349869/177057535-e8b6ecec-75f2-4280-9cc6-186c11028c5f.png)

+ w obiekcie user_data zwracaj jeszcze zmienna "type" proszę :)

2022-07-09 12:47 UTC, Dcisowski commented
Please Review, corrections added

2022-07-09 22:46 UTC, VenetianDevil requested changes
![image](https://user-images.githubusercontent.com/33349869/178124929-dde1d1f0-a71c-4ff5-a176-8ae5efe90269.png)
nadal przy rejestracji zwraca pusty obiekt user_data.

2022-07-11 08:35 UTC, Dcisowski commented
Please Review

2022-07-11 10:21 UTC, VenetianDevil approved these changes
Wydaje się działać 👍

2022-07-11 11:04 UTC, merged